name: Build

on:
  push:
    branches: [main]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup HashiCorp Packer
      uses: hashicorp/setup-packer@v2.0.0

    - name: Build AMI
      run: packer build aws-ubuntu.pkr.hcl
