name: Build

on:
  push:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup HashiCorp Packer
      uses: hashicorp/setup-packer@v2.0.0

    - name: Packer Init
      run: packer init .

    - name: Build AMI
      run: packer build .
