name: Continuous Deployment

on:
  push:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      ami_id: ${{ steps.extract.outputs.ami_id }}
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup HashiCorp Packer
      uses: hashicorp/setup-packer@v2.0.0

    - name: Packer Init
      run: packer init .

    - name: Build AMI
      run: packer build .

    - id: extract
      name: Extract AMI ID
      run: |
        ami_id=$(jq -r '.builds[0].artifact_id|split(":")[1]' ./manifest.json)
        echo "ami_id=$ami_id" >> "$GITHUB_OUTPUT"

  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
    -
      name: Deploy to AWS
      run: echo "Deploy to AWS using AMI ID ${{ needs.build.outputs.ami_id }}"
